In [1]:
import pandas as pd


In [2]:
df = pd.read_csv("./data/Animal Dataset.csv")
df.head()

Animal Height (cm) Weight (kg)         Color Lifespan (years)  \
0          Aardvark     105-130       40-65          Grey            20-30   
1          Aardwolf       40-50        8-14  Yellow-brown            10-12   
2  African Elephant     270-310   2700-6000          Grey            60-70   
3      African Lion      80-110     120-250           Tan            10-14   
4  African Wild Dog       75-80       18-36  Multicolored            10-12   

          Diet               Habitat           Predators Average Speed (km/h)  \
0  Insectivore  Savannas, Grasslands       Lions, Hyenas                   40   
1  Insectivore  Grasslands, Savannas     Lions, Leopards                24-30   
2    Herbivore      Savannah, Forest       Lions, Hyenas                   25   
3    Carnivore  Grasslands, Savannas  Hyenas, Crocodiles                   58   
4    Carnivore             Savannahs       Lions, Hyenas                   56   

               Countries Found Conservation Status           Family  \
0                       Africa       Least Concern  Orycteropodidae   
1  Eastern and Southern Africa       Least Concern        Hyaenidae   
2                       Africa          Vulnerable     Elephantidae   
3                       Africa          Vulnerable          Felidae   
4           Sub-Saharan Africa          Endangered          Canidae   

  Gestation Period (days) Top Speed (km/h) Social Structure  \
0                 210-240               40         Solitary   
1                      90               40         Solitary   
2                 640-660               40       Herd-based   
3                  98-105               80      Group-based   
4                      70               56      Group-based   

  Offspring per Birth  
0                   1  
1                 2-5  
2                   1  
3       2-4 (usually)  
4               10-12

In [3]:
df["Height (cm)"].unique()

array(['105-130', '40-50', '270-310', '80-110', '75-80', '67-101', '2-13',
       '152-186', '52-91', '140-160', '70-90', '25-30', 'Up to 120',
       '200-300', '200-250', '112-160', 'Up to 30', '35-37', '76-107',
       '70-102', '41-71', 'Up to 75', 'Up to 1100', 'Up to 60', '35-40',
       '90-110', '132-180', 'Not Applicable', '22-30', 'Up to 15',
       'Up to 33.5m', '81-85', 'Up to 20', 'Up to 150', '96-150',
       '200-400', '53-63', 'Up to 5', '70-120', 'Up to 460', '50-62',
       'Up to 160', 'Up to 180', '7-10', 'Up to 200', '20-36', '50-61',
       '50-55', '48-58', 'Up to 300', '140-188', '30-45', 'Up to 270',
       '100', '23-26', '14-30', '20-40', '15-25', 'Up to 40', 'Up to 90',
       '49-53', '48-53', 'Up to 183', 'Varies', '180-300', '80-105',
       'Up to 600', '2.2-7.7', 'Up to 320', 'Up to 366', 'Up to 35',
       '3-6', 'Up to 610', 'Up to 670', 'Up to 550', '130-160',
       'Up to 127', '86-107', '120-160', 'Up to 56', '7.5-13',
       'Up to 1700', '60-70

In [5]:
import re
def convert_height(value):
    if pd.isna(value):
        return 0
    
    value = str(value).strip()
    
    # Check for "number - number" format
    range_match = re.match(r'(\d+(?:\.\d+)?)\s*-\s*(\d+(?:\.\d+)?)', value)
    if range_match:
        start, end = map(float, range_match.groups())
        return (start + end) / 2
    
    # Check for "Up to number" format
    up_to_match = re.match(r'Up to (\d+(?:\.\d+)?)', value)
    if up_to_match:
        return float(up_to_match.group(1))
    
    # Check if it's a single number
    if value.replace('.', '', 1).isdigit():
        return float(value)
    
    # For any other format, return 0
    return 0

In [6]:
df['Height (cm)'] = df['Height (cm)'].apply(convert_height)

In [7]:
df["Height (cm)"].unique()

array([1.175e+02, 4.500e+01, 2.900e+02, 9.500e+01, 7.750e+01, 8.400e+01,
       7.500e+00, 1.690e+02, 7.150e+01, 1.500e+02, 8.000e+01, 2.750e+01,
       1.200e+02, 2.500e+02, 2.250e+02, 1.360e+02, 3.000e+01, 3.600e+01,
       9.150e+01, 8.600e+01, 5.600e+01, 7.500e+01, 1.100e+03, 6.000e+01,
       3.750e+01, 1.000e+02, 1.560e+02, 0.000e+00, 2.600e+01, 1.500e+01,
       3.350e+01, 8.300e+01, 2.000e+01, 1.230e+02, 3.000e+02, 5.800e+01,
       5.000e+00, 4.600e+02, 1.600e+02, 1.800e+02, 8.500e+00, 2.000e+02,
       2.800e+01, 5.550e+01, 5.250e+01, 5.300e+01, 1.640e+02, 2.700e+02,
       2.450e+01, 2.200e+01, 4.000e+01, 9.000e+01, 5.100e+01, 5.050e+01,
       1.830e+02, 2.400e+02, 9.250e+01, 6.000e+02, 4.950e+00, 3.200e+02,
       3.660e+02, 3.500e+01, 4.500e+00, 6.100e+02, 6.700e+02, 5.500e+02,
       1.450e+02, 1.270e+02, 9.650e+01, 1.400e+02, 1.025e+01, 1.700e+03,
       6.500e+01, 7.000e+01, 5.500e+01, 1.100e+01, 3.550e+01, 2.500e+01,
       4.750e+01, 8.850e+01, 3.500e+02, 8.700e+01, 

In [8]:
df["Weight (kg)"].unique()

array(['40-65', '8-14', '2700-6000', '120-250', '18-36', '19-120',
       'Up to 0.5', '318-1,000', '22-41', '380-1000', '65-90', '2.5-9',
       'Up to 6.7', '2000-5000', '500-620', '120-140', '18-40',
       'Up to 300', '2.2-2.7', '150-400', '3-6', '2-5', '5-13', '400-700',
       'Up to 600', '2.5-4', '220-260', '800-1,400', 'Up to 10',
       'Not Applicable', '0.07-0.12', 'Up to 0.028', 'Up to 200 tons',
       '1.5-3', 'Up to 0.3', '30-40', '30-82', '150-650', '25-32',
       'Up to 0.006', '70-780', 'Up to 90', '35-66', '20-72', '26-70',
       'Up to 65', '50-300', '100-135', '4.5-16', '23-32', '12-21',
       '13-20', 'Up to 420', '73-204', '2.5-6.5', 'Up to 20', '22-45',
       '300-400', '0.6-1.2', '0.8-1.6', 'Up to 55', 'Up to 1.1', '5-8',
       '1.5-2.5', '1.7-2.6', 'Up to 417', 'Varies', '600-1300', '28-52',
       'Up to 1500', 'Up to 25', '70-125', 'Up to 2.3', 'Up to 0.03',
       'Up to 210', 'Up to 0.7', 'Up to 2.4', 'Up to 2268', 'Up to 97.5',
       'Up to 200', 

In [9]:
df['Weight (kg)'] = df['Weight (kg)'].apply(convert_height)

In [10]:
df["Weight (kg)"].unique()

array([5.250e+01, 1.100e+01, 4.350e+03, 1.850e+02, 2.700e+01, 6.950e+01,
       5.000e-01, 1.595e+02, 3.150e+01, 6.900e+02, 7.750e+01, 5.750e+00,
       6.700e+00, 3.500e+03, 5.600e+02, 1.300e+02, 2.900e+01, 3.000e+02,
       2.450e+00, 2.750e+02, 4.500e+00, 3.500e+00, 9.000e+00, 5.500e+02,
       6.000e+02, 3.250e+00, 2.400e+02, 4.005e+02, 1.000e+01, 0.000e+00,
       9.500e-02, 2.800e-02, 2.000e+02, 2.250e+00, 3.000e-01, 3.500e+01,
       5.600e+01, 4.000e+02, 2.850e+01, 6.000e-03, 4.250e+02, 9.000e+01,
       5.050e+01, 4.600e+01, 4.800e+01, 6.500e+01, 1.750e+02, 1.175e+02,
       1.025e+01, 2.750e+01, 1.650e+01, 4.200e+02, 1.385e+02, 2.000e+01,
       3.350e+01, 3.500e+02, 9.000e-01, 1.200e+00, 5.500e+01, 1.100e+00,
       6.500e+00, 2.000e+00, 2.150e+00, 4.170e+02, 9.500e+02, 4.000e+01,
       1.500e+03, 2.500e+01, 9.750e+01, 2.300e+00, 3.000e-02, 2.100e+02,
       7.000e-01, 2.400e+00, 2.268e+03, 1.290e+02, 6.000e-01, 1.600e+02,
       6.750e+00, 2.250e+03, 3.000e+04, 1.150e+01, 

In [11]:
df["Lifespan (years)"].unique()

array(['20-30', '10-12', '60-70', '10-14', '15-20', '4-17', '25-30',
       '10-20', '3-6', '60-80', '20-25', '14-17', '10-15', '20-23',
       '7-10', 'Up to 30', '6-15', '6-8', '35-50', 'Up to 100',
       'Up to 130', '1-2 weeks', '70-90', '12-17', '6-8 months', '40-60',
       '35-45', '20-50', '1-2', '8-10', '40-50', 'Up to 70', '6-10',
       'Up to 60', '30-50', '15-18', '10-13', '70-80', '2-5', '15-23',
       'Up to 15', '100-150', 'Varies', '3-5', 'Up to 20', '10-14 days',
       '30-35', '10-17', '30-40', '70', '80-100', '80', 'Up to 300',
       '20-35', '25-35', 'Up to 20 years', '45-50', '60+', '25-50',
       'Up to 10', '15-25', '20-40', '12-14', '35-40', 'Up to 32',
       '50-60', 'Up to 5', '30-45', '5-10', '4-8', '4', '6-12', '3-10',
       'Up to 23', '8-12', 'Up to 21', '28-35', '10-16', '20-24', '10-25',
       '25-36', '12-25', 'Up to 4', '12-20', '5-8', '4-7', '5-20', '10',
       'Up to 28', '20-21', '70-100', '8-13', '7-12'], dtype=object)

In [12]:
df['Lifespan (years)'] = df['Lifespan (years)'].apply(convert_height)

In [13]:
df["Lifespan (years)"].unique()

array([ 25. ,  11. ,  65. ,  12. ,  17.5,  10.5,  27.5,  15. ,   4.5,
        70. ,  22.5,  15.5,  12.5,  21.5,   8.5,  30. ,   7. ,  42.5,
       100. , 130. ,   1.5,  80. ,  14.5,  50. ,  40. ,  35. ,   9. ,
        45. ,   8. ,  60. ,  16.5,  11.5,  75. ,   3.5,  19. , 125. ,
         0. ,   4. ,  20. ,  32.5,  13.5,  90. , 300. ,  47.5,  37.5,
        10. ,  13. ,  32. ,  55. ,   5. ,   7.5,   6. ,   6.5,  23. ,
        21. ,  31.5,  22. ,  30.5,  18.5,  16. ,   5.5,  28. ,  20.5,
        85. ,   9.5])

In [14]:
df["Average Speed (km/h)"].unique()

array(['40', '24-30', '25', '58', '56', '56-64', '0.1-1', '40-56', '24',
       '65', '55', '60', '16-32', '30-50', '40-64', '24-40', '0.8', '32',
       '48', '120', '16', '30', '14-28', 'Not Applicable', '25-35',
       '40-60', '37', '64', '1.6-2.4', '30-35', '112', '8', '1.6',
       '30-45', '40-45', '48-64', '10-15', '16-56', '2-2.5', '4-6',
       '40-50', '45-48', '29', '24-35', '6-7', '0.3-0.5', 'Varies',
       '30-40', '1-2', '1.6-3', '8-13', '0.3', '16-24 (in water)',
       '1.6-3.2', '35', '19-22', '50', '0.8-1.6', '40-80', '24-27',
       '70-80', '40-58', '2.5', '20', '6.4-9.6', '0.8-1', '24-29',
       '0.02-0.03', '0.03-0.08', '45', '6-12', '72', '3-7', '16-24',
       '0.5-0.7', '24-32', '88.5', '0.2-0.4', '26', '44', '14-16',
       '50-65', '0.03-0.24', '80', '1.2', '32-56', '40-72', '0.16-0.32',
       '28', '27', '29-42', '0.03', '17', '70', '22', '47', '56-70'],
      dtype=object)

In [15]:
df['Average Speed (km/h)'] = df['Average Speed (km/h)'].apply(convert_height)

In [16]:
df["Average Speed (km/h)"].unique()

array([4.00e+01, 2.70e+01, 2.50e+01, 5.80e+01, 5.60e+01, 6.00e+01,
       5.50e-01, 4.80e+01, 2.40e+01, 6.50e+01, 5.50e+01, 5.20e+01,
       3.20e+01, 8.00e-01, 1.20e+02, 1.60e+01, 3.00e+01, 2.10e+01,
       0.00e+00, 5.00e+01, 3.70e+01, 6.40e+01, 2.00e+00, 3.25e+01,
       1.12e+02, 8.00e+00, 1.60e+00, 3.75e+01, 4.25e+01, 1.25e+01,
       3.60e+01, 2.25e+00, 5.00e+00, 4.50e+01, 4.65e+01, 2.90e+01,
       2.95e+01, 6.50e+00, 4.00e-01, 3.50e+01, 1.50e+00, 2.30e+00,
       1.05e+01, 3.00e-01, 2.00e+01, 2.40e+00, 2.05e+01, 1.20e+00,
       2.55e+01, 7.50e+01, 4.90e+01, 2.50e+00, 9.00e-01, 2.65e+01,
       2.50e-02, 5.50e-02, 9.00e+00, 7.20e+01, 6.00e-01, 2.80e+01,
       8.85e+01, 3.00e-01, 2.60e+01, 4.40e+01, 1.50e+01, 5.75e+01,
       1.35e-01, 8.00e+01, 1.20e+00, 2.40e-01, 3.55e+01, 3.00e-02,
       1.70e+01, 7.00e+01, 2.20e+01, 4.70e+01, 6.30e+01])

In [17]:
df["Gestation Period (days)"].unique()

array(['210-240', '90', '640-660', '98-105', '70', '150', '10-15',
       '270-290', '190-210', '330-342', '52-60', 'Not Applicable', '40',
       '360-380', '300-350', '14-21', '160-170', '390-395', '34-36',
       '60-64', '165-200', '36-42 months', '40-70', '50-60', '104-106',
       '450-480', '17-18', '10-12 months', '41-45', '50-70', '220-230',
       '230-270', '12 months', '63', '21-35', '180-250', '88-100',
       '90-98', '230-240', '6-10', '260-330 million years', '40-80',
       '140-160', '60-63', '13-14 months', '255-270', '22-28', '10 weeks',
       '62-66', '140-145', '35', '50-52', '30-60', '140-150', '43-49',
       '38-40', '135', 'Varies', '275-280', '170-215', '94-123', '95-160',
       '120-150', '10-20', '125-130', '14', '12-18 months', '12-18',
       '150-160', '45-70', '45-75', '390-396', '335', '56-58', '230-250',
       '2 weeks', '13-22', '365', '63-67', '120-140', '1 week', '173-194',
       '21-24', '22-24', '90-113', '63-92', '7-8 months', '45-60',
     

In [18]:
df["Gestation Period (days)"] = df["Gestation Period (days)"].apply(convert_height)

In [19]:
df["Gestation Period (days)"].unique()

array([225. ,  90. , 650. , 101.5,  70. , 150. ,  12.5, 280. , 200. ,
       336. ,  56. ,   0. ,  40. , 370. , 325. ,  17.5, 165. , 392.5,
        35. ,  62. , 182.5,  39. ,  55. , 105. , 465. ,  11. ,  43. ,
        60. , 250. ,  63. ,  28. , 215. ,  94. , 235. ,   8. , 295. ,
        61.5,  13.5, 262.5,  25. ,  64. , 142.5,  51. ,  45. , 145. ,
        46. , 135. , 277.5, 192.5, 108.5, 127.5,  15. ,  14. , 155. ,
        57.5, 393. , 335. ,  57. , 240. , 365. ,  65. , 130. , 183.5,
        22.5,  23. ,  77.5,   7.5,  52.5, 136. , 160. , 407.5,  67.5,
       152.5,  71.5, 445. , 435. , 230. , 183. ,  27.5,  52. ,  32. ,
         6. ,  44. ,  32.5,  22. ,  24.5,  95. ,  33. , 247. , 100. ,
        19. , 535. , 450. , 185. , 120. , 195. , 124.5,  18.5, 128. ,
       126. , 125. ,  10.5, 190. , 255. , 245. , 270. , 175. ,  42.5,
       132. , 247.5,  85. , 272.5])

In [20]:
df["Top Speed (km/h)"].unique()

array(['40', '80', '56', '56-64', '0.8', '24', '65', '55', '60', '32',
       '40-64', '24-40', '0.2-0.3', '48', '120', '16', '30', '14-28',
       'Not Applicable', '39', '25-35', '40-60', '64', '1.6-2.4', '35',
       '112', '1.6', '37', '48-64', '27', '16-56', '4.8', '9', '4-6',
       '40-50', '45-48', '29', '24-35', '0.3', 'Varies', '30-40', '95',
       '8-13', '28', '50', '24-27', '70-80', '2.4', '20', '8', '30-50',
       '45', '58', '72', '16-24', '24-32', '88.5', '0.2-0.4', '26', '44',
       '14-16', '0.03-0.24', '1.2', '32-56', '40-72', '17', '70', '22',
       '47', '56-70', '25'], dtype=object)

In [21]:
df["Top Speed (km/h)"] = df["Top Speed (km/h)"].apply(convert_height)

In [22]:
df["Top Speed (km/h)"].unique()

array([ 40.   ,  80.   ,  56.   ,  60.   ,   0.8  ,  24.   ,  65.   ,
        55.   ,  32.   ,  52.   ,   0.25 ,  48.   , 120.   ,  16.   ,
        30.   ,  21.   ,   0.   ,  39.   ,  50.   ,  64.   ,   2.   ,
        35.   , 112.   ,   1.6  ,  37.   ,  27.   ,  36.   ,   4.8  ,
         9.   ,   5.   ,  45.   ,  46.5  ,  29.   ,  29.5  ,   0.3  ,
        95.   ,  10.5  ,  28.   ,  25.5  ,  75.   ,   2.4  ,  20.   ,
         8.   ,  58.   ,  72.   ,  88.5  ,   0.3  ,  26.   ,  44.   ,
        15.   ,   0.135,   1.2  ,  17.   ,  70.   ,  22.   ,  47.   ,
        63.   ,  25.   ])

In [23]:
df["Offspring per Birth"].unique()

array(['1', '2-5', '2-4 (usually)', '10-12', 'Up to 40', '4-11',
       'Not Applicable', '100-300', '1-3', '2-4', 'Up to 24', '2-6',
       '1 (rarely 2)', 'Up to 100', '3-8', 'Up to 1,000', '1-4', '30-80',
       '2-8', '3-5', '20-30', '6-9', '4-8', '1-10', 'Thousands', '1-2',
       '3-7', '10-60', '6-25', 'Up to 16', 'Varies', '20-95',
       'Up to 200,000', 'Up to 30', '2-14 (approx.)', '2-17', 'Up to 80',
       '1-4 (usually 1)', '20-40', '20-25', 'Up to 300', '8-16',
       'Hundreds', 'Up to 28', '4-6', 'Up to 10,000', '1-3 (rarely 5)',
       'Up to 400', '6-12', '2', 'Up to 10', '1-5', '3-11', '40-50',
       '2-10', '1-4 (usually 2-3)', '1-6', 'Up to 200', '4-32', '30-500',
       '1-14', '6-30', '1-1000', '2-20', '2-3', '10-50', '5-20',
       'Up to 25'], dtype=object)

In [24]:
df["Offspring per Birth"] = df["Offspring per Birth"].apply(convert_height)

In [25]:
df["Offspring per Birth"]

0       1.0
1       3.5
2       1.0
3       3.0
4      11.0
       ... 
200    30.0
201     1.0
202     0.0
203    12.5
204    25.0
Name: Offspring per Birth, Length: 205, dtype: float64

In [26]:
df.to_csv("./data/Animal Dataset Cleaned.csv", index=False)


In [33]:
import plotly.graph_objects as go
import pandas as pd
import numpy as np

In [37]:
large_families = df['Family'].value_counts().nlargest(10).index
df_large_families = df[df['Family'].isin(large_families)]


fig = go.Figure()
for family in large_families:
    fig.add_trace(go.Violin(y=df_large_families['Average Speed (km/h)'][df_large_families['Family'] == family],
                            x=df_large_families['Family'][df_large_families['Family'] == family],
                            name=family,
                            box_visible=True,
                            meanline_visible=True,
                            points='all',  # Show all data points
                            jitter=0.1,
                            scalemode='count',
                            ))

fig.update_layout(title="Average Speed Distribution for Large Animal Families",
                  yaxis_title="Average Speed (km/h)", xaxis_title="Family",
                  xaxis_tickangle=-45)
fig.show()